name: UpdateNordVPNlistOR

on:
  schedule:
    - cron: '0 */1 * * *'

  workflow_dispatch:

jobs:
  download-lists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download server lists
        run: |
          mkdir -p list
          declare -a countrycode=("au" "fr" "nl" "sg" "uk" "us")
          declare -a countryid=("13" "74" "153" "195" "227" "228")
          for (( i=0; i<${#countrycode[@]}; i++ ));
          do
            curl --silent "https://api.nordvpn.com/v1/servers/recommendations?filters\[country_id\]=${countryid[$i]}&filters\[servers_technologies\]\[identifier\]=openvpn_udp&limit=1000" | jq --raw-output '.[].hostname' | sort > list/${countrycode[$i]}.txt
          done
      
      - uses: actions/upload-artifact@v3
        with:
          name: server-lists
          path: list/

  test-servers:
    needs: download-lists
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        country: [au, fr, nl, sg, uk, us]
      max-parallel: 6
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v3
        with:
          name: server-lists
          path: list/
      
      - name: Test ${{ matrix.country }} servers
        env:
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PASS: ${{ secrets.VPS_PASS }}
          NORDVPN_USER: ${{ secrets.NORDVPN_USER }}
          NORDVPN_PASS: ${{ secrets.NORDVPN_PASS }}
        run: |
          sudo apt-get install -y sshpass
          mkdir -p list-IR
          
          # Test servers with extreme parallelization
          # ... (similar parallel testing logic for single country)
          
      - uses: actions/upload-artifact@v3
        with:
          name: results-${{ matrix.country }}
          path: list-IR/${{ matrix.country }}.txt

  commit-results:
    needs: test-servers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all results
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
      
      - name: Consolidate results
        run: |
          mkdir -p list list-IR
          cp artifacts/server-lists/list/* list/
          for country in au fr nl sg uk us; do
            cp artifacts/results-$country/$country.txt list-IR/ || touch list-IR/$country.txt
          done
          
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update server lists"
