name: CheckIPwithNordVPN

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:     # Manual trigger for testing

permissions:
  contents: write

jobs:
  check-ip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install NordVPN
      run: |
        wget -qO - https://repo.nordvpn.com/gpg/nordvpn_public.asc | sudo tee /etc/apt/trusted.gpg.d/nordvpn_public.asc
        echo "deb https://repo.nordvpn.com/deb/nordvpn/debian stable main" | sudo tee /etc/apt/sources.list.d/nordvpn.list
        sudo apt update
        sudo apt install -y nordvpn
        
    - name: Connect to NordVPN
      env:
        NORDVPN_TOKEN: ${{ secrets.NORDVPN_TOKEN }}
      run: |
        # Login
        sudo nordvpn login --token $NORDVPN_TOKEN
        
        # Configure settings
        sudo nordvpn set protocol udp || true
        sudo nordvpn set technology openvpn || true
        
        # Show available French servers for debugging
        echo "Available French servers:"
        sudo nordvpn cities france
        
        # Disconnect if already connected
        sudo nordvpn disconnect || true
        
        # Connect specifically to server number
        echo "Connecting to France server #1031..."
        sudo nordvpn connect France 1031
        
        # Wait for connection
        echo "Waiting for VPN connection to establish..."
        for i in {1..20}; do
          if sudo nordvpn status | grep -q "Connected"; then
            echo "Connected after $i seconds"
            break
          fi
          sleep 1
        done
        
        # Show full status
        echo "=== VPN Status ==="
        sudo nordvpn status
        echo "=================="
        
        # Test connection
        echo "Testing connection..."
        curl -s https://nordvpn.com/api/server/stats | grep -q "fr1031" && echo "Server confirmed: fr1031" || echo "Warning: Server mismatch"
        
    - name: Check IP and save
      run: |
        echo "=== Connection Details ==="
        sudo nordvpn status
        echo ""
        
        # Get IP multiple times to ensure consistency
        echo "Checking IP (attempt 1):"
        IP1=$(curl -s https://checkip.amazonaws.com/)
        echo "$IP1"
        
        sleep 2
        
        echo "Checking IP (attempt 2):"
        IP2=$(curl -s https://checkip.amazonaws.com/)
        echo "$IP2"
        
        if [ "$IP1" != "$IP2" ]; then
          echo "Warning: IP changed between checks!"
        fi
        
        # Save the IP
        echo "$IP1" > ip.txt
        echo ""
        echo "Final IP saved: $IP1"
        
    - name: Commit IP file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ip.txt
        git commit -m "Update IP - $(date)" || echo "No changes"
        git push || echo "No changes to push"
        
    - name: Disconnect VPN
      if: always()
      run: sudo nordvpn disconnect || true
