name: CheckIPviaNORD

on:
  workflow_dispatch:
    inputs:
      server:
        required: true
        default: 'fr1031.nordvpn.com'
  schedule:
    - cron: '0 * * * *'  # Every hour

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - run: |
        # Install NordVPN
        wget -qO - https://repo.nordvpn.com/gpg/nordvpn_public.asc | sudo apt-key add -
        echo "deb https://repo.nordvpn.com/deb/nordvpn/debian stable main" | sudo tee /etc/apt/sources.list.d/nordvpn.list
        sudo apt update && sudo apt install nordvpn -y
        
        # Login (requires credentials in secrets)
        nordvpn login --username ${{ secrets.NORDVPN_USER }} --password ${{ secrets.NORDVPN_PASS }}
        
        # Connect to server
        nordvpn connect ${{ inputs.server || 'fr1031.nordvpn.com' }}
        
        # Check IP and save to file
        echo "Connected to: ${{ inputs.server || 'fr1031.nordvpn.com' }}"
        IP=$(curl -s https://checkip.amazonaws.com/)
        echo "IP: $IP"
        echo "$IP" > ip.txt
        echo "$(date): $IP" >> ip_history.txt
    
    - uses: actions/upload-artifact@v4
      with:
        name: nordvpn-ip-files
        path: |
          ip.txt
          ip_history.txt
