name: CheckIPwithNordVPN

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:     # Manual trigger for testing

permissions:
  contents: write

jobs:
  check-ip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install NordVPN
      run: |
        wget -qO - https://repo.nordvpn.com/gpg/nordvpn_public.asc | sudo tee /etc/apt/trusted.gpg.d/nordvpn_public.asc
        echo "deb https://repo.nordvpn.com/deb/nordvpn/debian stable main" | sudo tee /etc/apt/sources.list.d/nordvpn.list
        sudo apt update
        sudo apt install -y nordvpn
        
    - name: Connect to NordVPN
      env:
        NORDVPN_TOKEN: ${{ secrets.NORDVPN_TOKEN }}
      run: |
        sudo nordvpn login --token $NORDVPN_TOKEN
        sudo nordvpn set protocol udp || true
        
        # Explicitly connect to fr1031
        echo "Connecting to fr1031..."
        sudo nordvpn connect fr1031
        
        # Wait for connection and verify
        echo "Waiting for VPN connection..."
        sleep 10
        
        # Verify connection and server
        if sudo nordvpn status | grep -q "Connected"; then
          echo "Successfully connected to NordVPN"
          sudo nordvpn status
          
          # Double-check we're on fr1031
          if sudo nordvpn status | grep -q "fr1031"; then
            echo "Confirmed: Connected to fr1031"
          else
            echo "Warning: Connected but not to fr1031"
          fi
        else
          echo "Failed to connect to NordVPN"
          sudo nordvpn status
          exit 1
        fi
        
    - name: Check IP and save
      run: |
        echo "Checking connection..."
        sudo nordvpn status
        echo "---"
        IP=$(curl -s https://checkip.amazonaws.com/)
        echo "$IP" > ip.txt
        echo "Current IP: $IP"
        
    - name: Commit IP file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ip.txt
        git commit -m "Update IP - $(date)" || echo "No changes"
        git push || echo "No changes to push"
        
    - name: Disconnect VPN
      if: always()
      run: sudo nordvpn disconnect || true
